[project]
name = "water-info-acquirer"
version = "0.1.1"
description = "水文水質データベースからデータから水位・流量・雨量データを指定期間ごとに取得する。"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "pandas>=2.3.3",
    "requests>=2.32.5",
    "xlsxwriter>=3.2.9",
]
